---
- name: Remove Nginx with custom HTML
  hosts: up_dev
  become: true
  vars:
    destin_folder: /usr/share/nginx/html
    destin_file: "{{ destin_folder }}/index.html"

  tasks:
    - block: # =======DEBIAN=======

      - name: Remove Nginx on Debian
        when: ansible_os_family == 'Debian'
        become: true
        apt:
          name: "nginx"
          state: absent
          purge: yes
      when: ansible_os_family == 'Debian'

    - block: # =======AMZ LINUX=======
      - name: Remove Nginx on RedHat/AMZ Linux
        become: true
        dnf:
          name: nginx
          state: absent
      when: ansible_os_family == 'RedHat'

