---
- name: Up nginx with custom HTML
  hosts: debian
  become: true
  vars:
    source: ../tmp2
    source_j2: "{{source}}/j2/index.j2"
    destin_folder: /usr/share/nginx/html
    destin_file: "{{ destin_folder }}/index.html"
    nginx_version: 1.26.0 

  tasks:
  - name: Ensure gnupg is installed (for APT key management)
    when: ansible_os_family == 'Debian'
    become: true
    apt:
      name: gnupg
      state: present
      update_cache: yes

  - name: Adding APT repository key
    when: ansible_os_family == 'Debian'
    become: true
    apt_key:
      url: "http://nginx.org/keys/nginx_signing.key"
      state: present

  - name: Add official APT repository
    when: ansible_os_family == 'Debian'
    become: true
    apt_repository:
      repo: "deb http://nginx.org/packages/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx"
      state: present

  - name: Install Nginx on Debian
    when: ansible_os_family == 'Debian'
    become: true
    apt: 
      name: "nginx"
      state: present
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Nginx using dnf (for non-Debian systems)
    when: ansible_pkg_mgr == "dnf"
    become: true
    dnf:
      name: nginx
      state: present
    register: install_result

  - name: Start and enable Nginx
    become: true
    systemd:
      name: nginx
      state: started
      enabled: true
    register: nginx_status

  - name: Remove the file {{ destin_file }}
    file:
      path: "{{ destin_file }}"
      state: absent
    when: nginx_status.state == "started"

  - name: Copy only jpegs
    copy:
      src: "{{ item }}"
      dest: "{{ destin_folder }}/"
    with_fileglob: "{{ source }}/*.jpeg"
    notify: Restart Nginx

  - name: Generate Template
    template: 
      src: "{{source_j2}}"
      dest: "{{ destin_file }}"
    notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      become: true
      service:
        name: nginx
        state: restarted
