- name: delegate_learn
  hosts: "{{host}}"
  become: true

  vars:
    env: rabotu

  tasks:
    - name: Ping servers
      ping:

    - name: Understanding
      become: true
      shell: echo server is {{inventory_hostname}} dereg from alb node name os {{ansible_nodename}} >> /home/log_delete.txt
      delegate_to: amazon-linux-dev 

    - name: Create File1
      copy:
        dest: /home/file1.txt
        content: |
          qwertyu, hochu
          asdfghj, nayti
          zxcvbnm, {{env}}
      delegate_to: debian-dev

    - name: Create File2
      copy:
        dest: /home/file2.txt
        content: |
          qwertyu, hochu
          asdfghj, nayti
          zxcvbnm, {{env}}
    - name: Update db 
      shell: echo   Update db ..................
      run_once: true

    - name: Reboot
      shell: sleep 3 && reboot now
      async: 1
      poll: 0

    - name: wait untill servers up
      wait_for:
        host: "{{inventory_hostname}}"
        state: started
        delay: 5
        timeout: 40
      delegate_to: 127.0.0.1