- name: delegate_learn
  hosts: amazon
  any_errors_fatal: true
  become: true

  tasks:
    - name: Install tree
      dnf:
        name: treeee
        state: present
      ignore_errors: yes
    
    - name: 2 task
      shell: cat /home/ec2-user/nemo.txt
      register: results



    # - name: 2 task
    #   shell: echo hello my perrronu
    #   register: results
    #   failed_when: results.rc == 0
      #failed_when: "'my' in results.stdout" 

    - debug:
        var: results

    - name: 3 task
      shell: echo sdlkfgnsdflgnsdkjfgnsdfjgnjklsdfngfdjkg